#!/usr/bin/env bash

docker run --rm  -v "$(pwd)":/opt/project "$(docker build -q -f=docker/php.dockerfile .)" /bin/bash -c \
  "php /root/.composer/vendor/bin/phpcs --standard=psr2 src \
&& php /root/.composer/vendor/bin/phpunit\
&& php /root/.composer/vendor/bin/phpmd src text phpmd.xml\
&& php /root/.composer/vendor/bin/phpcpd src\
&& php /root/.composer/vendor/bin/phpmnd src --non-zero-exit-on-violation\
&& php /root/.composer/vendor/bin/phpdoccheck -d src\
&& php /root/.composer/vendor/bin/phpcs --standard=psr2 src\
&& php /root/.composer/vendor/bin/phpstan analyze src --level=1\
&& php /opt/project/bin/phpcdm src --non-zero-exit-on-violation
"
if [ $? != 0 ]; then
  echo "Fix errors before commit."
  echo "Try run \
  docker run --rm -v \"\$(pwd)\":/opt/project \"\$(docker build -q -f=docker/php.dockerfile .)\" \
  php /root/.composer/vendor/bin/phpcbf --standard=psr2 src"
  exit 1
fi
